// ignore_for_file: public_member_api_docs
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

/// Predefined text styles for the Lynk-X ecosystem.
///
/// This file is auto-generated from theme/tokens.json.
/// Do not edit this file manually.
class AppTypography {
  /// Text style: h1 (32px, weight: 700)
  static TextStyle get h1 => GoogleFonts.interTight(
        fontSize: 32,
        fontWeight: FontWeight.w700,
        letterSpacing: -0.5,
      );

  /// Text style: h2 (24px, weight: 600)
  static TextStyle get h2 => GoogleFonts.interTight(
        fontSize: 24,
        fontWeight: FontWeight.w600,
        letterSpacing: -0.4,
      );

  /// Text style: bodyLarge (16px, weight: 400)
  static TextStyle get bodyLarge => GoogleFonts.inter(
        fontSize: 16,
        fontWeight: FontWeight.w400,
      );

  /// Text style: bodyMedium (14px, weight: 400)
  static TextStyle get bodyMedium => GoogleFonts.inter(
        fontSize: 14,
        fontWeight: FontWeight.w400,
      );

  /// Text style: labelLarge (14px, weight: 500)
  static TextStyle get labelLarge => GoogleFonts.inter(
        fontSize: 14,
        fontWeight: FontWeight.w500,
      );

  static TextStyle interTight({
    double? fontSize,
    FontWeight? fontWeight,
    Color? color,
    double? height,
    double? letterSpacing,
  }) =>
      GoogleFonts.interTight(
        fontSize: fontSize,
        fontWeight: fontWeight,
        color: color,
        height: height,
        letterSpacing: letterSpacing,
      );

  static TextStyle inter({
    double? fontSize,
    FontWeight? fontWeight,
    Color? color,
    double? height,
    double? letterSpacing,
  }) =>
      GoogleFonts.inter(
        fontSize: fontSize,
        fontWeight: fontWeight,
        color: color,
        height: height,
        letterSpacing: letterSpacing,
      );
}
