// ignore_for_file: public_member_api_docs
import 'package:flutter/material.dart';

/// Centralized color palette for the Lynk-X ecosystem.
/// 
/// This file is auto-generated from theme/tokens.json.
/// Do not edit this file manually.
class AppColors {
  // --- Brand Colors ---
  /// Brand color: primary (#20f928)
  static const Color primary = Color(0xFF20f928);
  /// Brand color: secondary (#f9c920)
  static const Color secondary = Color(0xFFf9c920);
  /// Brand color: tertiary (#322f35)
  static const Color tertiary = Color(0xFF322f35);
  /// Brand color: alternate (#e0e3e7)
  static const Color alternate = Color(0xFFe0e3e7);
  /// Brand color: userLocation (#FF0000)
  static const Color userLocation = Color(0xFFFF0000);

  // --- Utility Colors ---
  /// Utility color: primaryText (#ffffff)
  static const Color primaryText = Color(0xFFffffff);
  /// Utility color: secondaryText (#000000)
  static const Color secondaryText = Color(0xFF000000);
  /// Utility color: primaryBackground (#000000)
  static const Color primaryBackground = Color(0xFF000000);
  /// Utility color: secondaryBackground (#ffffff)
  static const Color secondaryBackground = Color(0xFFffffff);

  // --- Interface Colors ---
  /// Interface color: success (#0F8C16)
  static const Color success = Color(0xFF0F8C16);
  /// Interface color: error (#d32f2f)
  static const Color error = Color(0xFFd32f2f);
  /// Interface color: surface (#1E1E1E)
  static const Color surface = Color(0xFF1E1E1E);
  /// Interface color: outline (#E0E0E0)
  static const Color outline = Color(0xFFE0E0E0);
}
