// ignore_for_file: public_member_api_docs
import 'package:flutter/material.dart';

/// Standard elevation and shadow effects for the Lynk-X ecosystem.
/// 
/// This file is auto-generated from theme/tokens.json.
/// Do not edit this file manually.
class AppShadows {
  /// Shadow level: sm
  static List<BoxShadow> get sm => [
    BoxShadow(
      color: Color(0x1a000000),
      offset: Offset(0, 1),
      blurRadius: 2,
      spreadRadius: 0,
    ),
  ];

  /// Shadow level: md
  static List<BoxShadow> get md => [
    BoxShadow(
      color: Color(0x26000000),
      offset: Offset(0, 4),
      blurRadius: 6,
      spreadRadius: -1,
    ),
  ];

  /// Shadow level: lg
  static List<BoxShadow> get lg => [
    BoxShadow(
      color: Color(0x33000000),
      offset: Offset(0, 10),
      blurRadius: 15,
      spreadRadius: -3,
    ),
  ];
}
