// ignore_for_file: public_member_api_docs
import 'package:flutter/material.dart';

/// Standard dimensions, spacing, and radius tokens for the Lynk-X ecosystem.
/// 
/// This file is auto-generated from theme/tokens.json.
/// Do not edit this file manually.
class AppDimensions {
  // --- Spacing ---
  /// Spacing: xs (4px)
  static const double spacingXs = 4;
  /// Spacing: sm (8px)
  static const double spacingSm = 8;
  /// Spacing: md (12px)
  static const double spacingMd = 12;
  /// Spacing: lg (16px)
  static const double spacingLg = 16;
  /// Spacing: xl (24px)
  static const double spacingXl = 24;
  /// Spacing: xxl (32px)
  static const double spacingXxl = 32;
  /// Spacing: huge (48px)
  static const double spacingHuge = 48;

  // --- Border Radius ---
  /// Radius value: xs (2px)
  static const double radiusXs = 2;
  /// BorderRadius object: xs (2px)
  static BorderRadius get borderRadiusXs => BorderRadius.circular(2);
  /// Radius value: sm (4px)
  static const double radiusSm = 4;
  /// BorderRadius object: sm (4px)
  static BorderRadius get borderRadiusSm => BorderRadius.circular(4);
  /// Radius value: md (8px)
  static const double radiusMd = 8;
  /// BorderRadius object: md (8px)
  static BorderRadius get borderRadiusMd => BorderRadius.circular(8);
  /// Radius value: lg (12px)
  static const double radiusLg = 12;
  /// BorderRadius object: lg (12px)
  static BorderRadius get borderRadiusLg => BorderRadius.circular(12);
  /// Radius value: xl (16px)
  static const double radiusXl = 16;
  /// BorderRadius object: xl (16px)
  static BorderRadius get borderRadiusXl => BorderRadius.circular(16);
  /// Radius value: xxl (20px)
  static const double radiusXxl = 20;
  /// BorderRadius object: xxl (20px)
  static BorderRadius get borderRadiusXxl => BorderRadius.circular(20);
  /// Radius value: full (9999px)
  static const double radiusFull = 9999;
  /// BorderRadius object: full (9999px)
  static BorderRadius get borderRadiusFull => BorderRadius.circular(9999);

  // --- Icon Sizes ---
  /// Icon size: xs (16px)
  static const double iconXs = 16;
  /// Icon size: sm (20px)
  static const double iconSm = 20;
  /// Icon size: md (24px)
  static const double iconMd = 24;
  /// Icon size: lg (32px)
  static const double iconLg = 32;
  /// Icon size: xl (48px)
  static const double iconXl = 48;
}
