const fs = require('fs');
const path = require('path');

const TOKENS_PATH = path.join(__dirname, '../theme/tokens.json');
const CORE_THEME_DIR = path.join(__dirname, '../lib/src/theme');
const TS_TOKENS_PATH = path.join(__dirname, '../../../web/src/theme/tokens.ts');
const CSS_THEME_PATH = path.join(__dirname, '../../../web/src/app/theme.css');

const tokens = JSON.parse(fs.readFileSync(TOKENS_PATH, 'utf8'));

// Helper to convert hex #RRGGBB to 0xFFRRGGBB
function toColorInt(hex) {
    if (hex.startsWith('rgba')) {
        const parts = hex.match(/[\d.]+/g);
        const r = parseInt(parts[0]).toString(16).padStart(2, '0');
        const g = parseInt(parts[1]).toString(16).padStart(2, '0');
        const b = parseInt(parts[2]).toString(16).padStart(2, '0');
        const a = Math.round(parseFloat(parts[3]) * 255).toString(16).padStart(2, '0');
        return `0x${a}${r}${g}${b}`;
    }
    return `0xFF${hex.substring(1)}`;
}

function writeDartFile(filename, content) {
    fs.writeFileSync(path.join(CORE_THEME_DIR, filename), content);
    console.log(`Generated ${path.join(CORE_THEME_DIR, filename)}`);
}

// Generate AppColors.dart
function generateDartColors() {
    let content = `// ignore_for_file: public_member_api_docs
import 'package:flutter/material.dart';

/// Centralized color palette for the Lynk-X ecosystem.
/// 
/// This file is auto-generated from theme/tokens.json.
/// Do not edit this file manually.
class AppColors {`;
    Object.entries(tokens.colors).forEach(([category, values]) => {
        const formattedCategory = category.charAt(0).toUpperCase() + category.slice(1);
        content += `\n  // --- ${formattedCategory} Colors ---\n`;
        Object.entries(values).forEach(([key, value]) => {
            content += `  /// ${formattedCategory} color: ${key} (${value})
  static const Color ${key} = Color(${toColorInt(value)});\n`;
        });
    });
    content += '}\n';
    writeDartFile('app_colors.dart', content);
}

// Generate AppTypography.dart
function generateDartTypography() {
    let content = `// ignore_for_file: public_member_api_docs
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

/// Predefined text styles for the Lynk-X ecosystem.
/// 
/// This file is auto-generated from theme/tokens.json.
/// Do not edit this file manually.
class AppTypography {`;
    Object.entries(tokens.typography.styles).forEach(([key, style]) => {
        const fontFamilyMethod = style.family === 'heading' ? 'interTight' : 'inter';
        const fontWeight = `FontWeight.w${style.fontWeight}`;
        let params = [];
        if (style.fontSize) params.push(`fontSize: ${style.fontSize}`);
        if (style.fontWeight) params.push(`fontWeight: ${fontWeight}`);
        if (style.letterSpacing) params.push(`letterSpacing: ${style.letterSpacing}`);

        content += `\n  /// Text style: ${key} (${style.fontSize}px, weight: ${style.fontWeight})
  static TextStyle get ${key} => GoogleFonts.${fontFamilyMethod}(\n`;
        params.forEach(p => content += `        ${p},\n`);
        content += `      );\n`;
    });
    content += '}\n';
    writeDartFile('app_typography.dart', content);
}

// Generate AppDimensions.dart (Spacing, Radius, Icons)
function generateDartDimensions() {
    let content = `// ignore_for_file: public_member_api_docs
import 'package:flutter/material.dart';

/// Standard dimensions, spacing, and radius tokens for the Lynk-X ecosystem.
/// 
/// This file is auto-generated from theme/tokens.json.
/// Do not edit this file manually.
class AppDimensions {`;

    // Spacing
    content += '\n  // --- Spacing ---\n';
    Object.entries(tokens.spacing).forEach(([key, value]) => {
        content += `  /// Spacing: ${key} (${value}px)
  static const double spacing${key.charAt(0).toUpperCase() + key.slice(1)} = ${value};\n`;
    });

    // Radius
    content += '\n  // --- Border Radius ---\n';
    Object.entries(tokens.radius).forEach(([key, value]) => {
        const radiusName = key.charAt(0).toUpperCase() + key.slice(1);
        content += `  /// Radius value: ${key} (${value}px)
  static const double radius${radiusName} = ${value};
  /// BorderRadius object: ${key} (${value}px)
  static BorderRadius get borderRadius${radiusName} => BorderRadius.circular(${value});\n`;
    });

    // Icons
    content += '\n  // --- Icon Sizes ---\n';
    Object.entries(tokens.icons).forEach(([key, value]) => {
        content += `  /// Icon size: ${key} (${value}px)
  static const double icon${key.charAt(0).toUpperCase() + key.slice(1)} = ${value};\n`;
    });

    content += '}\n';
    writeDartFile('app_dimensions.dart', content);
}

// Generate AppShadows.dart
function generateDartShadows() {
    let content = `// ignore_for_file: public_member_api_docs
import 'package:flutter/material.dart';

/// Standard elevation and shadow effects for the Lynk-X ecosystem.
/// 
/// This file is auto-generated from theme/tokens.json.
/// Do not edit this file manually.
class AppShadows {`;
    Object.entries(tokens.shadows).forEach(([key, shadow]) => {
        content += `\n  /// Shadow level: ${key}
  static List<BoxShadow> get ${key} => [
    BoxShadow(
      color: Color(${toColorInt(shadow.color)}),
      offset: Offset(${shadow.offset.x}, ${shadow.offset.y}),
      blurRadius: ${shadow.blur},
      spreadRadius: ${shadow.spread},
    ),
  ];\n`;
    });
    content += '}\n';
    writeDartFile('app_shadows.dart', content);
}

// Generate tokens.ts (Web)
function generateWebTokens() {
    const content = `/**
 * Shared design tokens for the Lynk-X web application.
 * 
 * This file is auto-generated from theme/tokens.json.
 * Do not edit this file manually.
 */
export const tokens = ${JSON.stringify(tokens, null, 2)} as const;\n`;

    // Ensure directory exists
    const dir = path.dirname(TS_TOKENS_PATH);
    if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
    }

    fs.writeFileSync(TS_TOKENS_PATH, content);
    console.log(`Generated ${TS_TOKENS_PATH}`);
}

// Generate theme.css (Web)
function generateWebCSS() {
    let content = `/**
 * Shared design tokens as CSS variables for the Lynk-X web application.
 * 
 * This file is auto-generated from theme/tokens.json.
 * Do not edit this file manually.
 */\n\n:root {\n`;

    // Colors
    Object.entries(tokens.colors).forEach(([category, values]) => {
        Object.entries(values).forEach(([key, value]) => {
            content += `  --color-${category}-${key}: ${value};\n`;
        });
    });

    // Spacing
    content += '\n';
    Object.entries(tokens.spacing).forEach(([key, value]) => {
        content += `  --spacing-${key}: ${value}px;\n`;
    });

    // Radius
    content += '\n';
    Object.entries(tokens.radius).forEach(([key, value]) => {
        content += `  --radius-${key}: ${value}px;\n`;
    });

    // Icons
    content += '\n';
    Object.entries(tokens.icons).forEach(([key, value]) => {
        content += `  --icon-${key}: ${value}px;\n`;
    });

    // Typography Families
    content += '\n';
    Object.entries(tokens.typography.fontFamilies).forEach(([key, value]) => {
        content += `  --font-${key}: ${value};\n`;
    });

    content += '}\n';

    // Ensure directory exists
    const dir = path.dirname(CSS_THEME_PATH);
    if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
    }

    fs.writeFileSync(CSS_THEME_PATH, content);
    console.log(`Generated ${CSS_THEME_PATH}`);
}

generateDartColors();
generateDartTypography();
generateDartDimensions();
generateDartShadows();
generateWebTokens();
generateWebCSS();
